// -----------------------------------------------------------------------------
// Changelog generation config (`conventional-changelog`, conventionalcommits
// preset).
//
// Used by the Release workflow (.github/workflows/release.yml), which runs
// `npx conventional-changelog -n ./changelog.config.mjs -i CHANGELOG.md -s -r 1`
// between the version bump and the release commit, so CHANGELOG.md travels in
// the same `chore(release): X.Y.Z` commit as the bumped manifest.
//
// Why an explicit `types` list instead of the preset default: the default only
// surfaces `feat` and `fix`. This integration also ships meaningful `docs`,
// `refactor`, `perf`, `build` and `chore` work (SDK bumps, manifest changes),
// and a release whose whole content is hidden would produce an empty section --
// exactly what a changelog must avoid. Only the release commits themselves are
// hidden, since they merely repeat the version heading right above them.
// -----------------------------------------------------------------------------

import createPreset from 'conventional-changelog-conventionalcommits';

export default createPreset({
  types: [
    { type: 'feat', section: 'Features' },
    { type: 'fix', section: 'Bug Fixes' },
    { type: 'perf', section: 'Performance' },
    { type: 'refactor', section: 'Refactoring' },
    { type: 'docs', section: 'Documentation' },
    { type: 'test', section: 'Tests' },
    { type: 'build', section: 'Build System' },
    { type: 'ci', section: 'Continuous Integration' },
    // `chore(release): X.Y.Z` is generated by the Release workflow itself and
    // would only repeat the version heading right above it. `effect: 'hidden'`
    // (not `hidden: true`, which this preset ignores) keeps it out, and the
    // scoped entry must come BEFORE the catch-all `chore` below to win.
    { type: 'chore', scope: 'release', effect: 'hidden' },
    { type: 'chore', section: 'Miscellaneous' },
  ],
});
